---
- name: Install PostgreSQL and Dependencies
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes
  become: true

- name: Ensure PostgreSQL is running and enabled
  service:
    name: postgresql
    state: started
    enabled: yes
  become: true


